"use client";

import { SessionProvider } from "next-auth/react";
import Header from "./components/layout/header";
import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/app/context/client-provider";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import Footer from "./components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blogee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
