import Layout from "./components/layout/layout";
import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/app/context/client-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blogee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Layout>{children}</Layout>
        </Provider>
      </body>
    </html>
  );
}
